---
- hosts: nexus
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - roles/nexus-server/vars/main.yml
  handlers:
    - include: roles/nexus-server/handlers/main.yml
  roles:
    - role: roles/nexus-server

- hosts: sonarqube
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - roles/sonarqube/vars/main.yml
  handlers:
    - include: roles/sonarqube/handlers/main.yml
  roles:
    - role: roles/sonarqube
  
- hosts: tomcat
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - roles/tomcat/vars/main.yml
  handlers:
    - include: roles/tomcat/handlers/main.yml
  roles:
    - role: roles/tomcat

